spring:
  datasource:
    url: jdbc:mysql://210.221.219.131:3306/skeletone
    username: root
    password: 0625
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    locale: ko_KR    
  messages:
    cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
    basename: classpath:/message # Comma-separated list of basenames, each following the ResourceBundle convention.
    encoding: UTF-8 # Message bundles encoding.
